name: Exercícios 4º bimestre

on:
  push:
  workflow_dispatch:

jobs:
  ex01-loop-while:
    name: ex01-loop-while
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 4-bimestre/ex01-loop-while
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm test